language: swift
osx_image: xcode10
xcode_project: Point.xcworkspace # path to your xcodeproj folder
xcode_scheme: Point
xcode_destination: platform=iOS Simulator, OS=11.4, name=iPhone X

script:
  - if [[ "$TRAVIS_BRANCH" == "develop" ]]; then
  -   fastlane fabric
  - elif [[ "$TRAVIS_BRANCH" == "release" ]]; then
  -   fastlane testflight_beta version:1.0
  - else
  -   echo "The file 'somefile' does not exist."
  - fi
branches:
  only:
    - develop
    - release
    - master
