language: swift
osx_image: xcode10
xcode_project: Point.xcworkspace # path to your xcodeproj folder
xcode_scheme: Point
xcode_destination: platform=iOS Simulator, OS=11.4, name=iPhone X
before_install:
  - sudo gem install fastlane -NV
  - sudo gem install cocoapods --pre
script:
  - if [[ $TRAVIS_BRANCH == "develop"]]; then fastlane fabric; fi
  - if [[ $TRAVIS_BRANCH == "release"]]; then fastlane testflight_beta version:1.0; fi
branches:
  only:
    - develop
    - release
    - master
