language: swift
osx_image: xcode10
xcode_project: Point.xcworkspace # path to your xcodeproj folder
xcode_scheme: Point
xcode_destination: platform=iOS Simulator, OS=11.4, name=iPhone X

script:
  - sh build.sh
branches:
  only:
    - develop
    - release
    - master
